### ISSUE TITLE
Error creating commit: Invalid request

### ISSUE THREAD

**Issue by TheHolyWaffle** [github/maven-plugins#69]
```
[INFO] --- site-maven-plugin:0.9:site (execution1) @ lolchatapi ---
[INFO] Creating 18 blobs
[INFO] Creating tree with 19 blob entries
[INFO] Merging with tree 9a11f1f5c5d4e3441cb3949dcf9e907fa6c1f1d0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.494 s
[INFO] Finished at: 2014-08-29T12:09:59+02:00
[INFO] Final Memory: 31M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.9:site (execution1) on project lolchatapi: Error creating commit: Invalid request.
[ERROR] 
[ERROR] Expected data to be of type "object"; value was: nil.
[ERROR] Expected data to be of type "object"; value was: nil. (422)

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating commit: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:440)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.eclipse.egit.github.core.service.DataService.createCommit(DataService.java:397)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:434)
	... 22 more
```

Everything worked great 5 days ago, but today I started getting this error. Is there anything on my end that I can do?

**Comment by camilolopes** [comment]
hi guys, I am passing for this problem. I have updated my profile with email. But I am not getting to deploy mvn deploy. 
Any idea?

**Comment by farolfo** [comment]
Still with the same issue in 0.10. This was released with the PR submitted above?

**Comment by brianoliver** [comment]
I gave up on it being fixed in github.   I created a branch locally and published a "fixed build" which we use for all publishing.  One day when it's resolved we'll use the "fixed" version, but until then, we'll carry on without it.

**Comment by farolfo** [comment]
This is still failing on my en pinging to 0.11 :/, getting:

[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.11:site (default) on project MY-PROJECT: Error creating commit: Invalid request.
[ERROR] 
[ERROR] Expected data to be of type "string"; value was: nil.
[ERROR] Expected data to be of type "string"; value was: nil. (422)

What I did is to put in the settings.xml username and password that are different from the one set to git but that are allowed to push to the gh-pages branch.

**Comment by angleto** [comment]
I had the same problem with the version 0.11, I solved it by setting the real name on my github profile (https://github.com/github/maven-plugins/issues/85)

**Comment by zkejid** [comment]
Similar issue.

> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.github:site-maven-plugin:0.13-SNAPSHOT:site (default) on project threads: Error creating c
> ommit: Invalid request.
> 
> nil is not a string.
> nil is not a string. (422)

Not able to push artifacts: http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github/14013645#14013645

**Comment by iToto** [comment]
Getting the same issue as @zkejid anyone know which string is nil? (Using v0.10)
